CREATE TABLE ad_plans (
id VARCHAR(50) PRIMARY KEY,
name VARCHAR(50) NOT NULL,
name_fa VARCHAR(50) NOT NULL,
price BIGINT NOT NULL,
max_ads INTEGER DEFAULT 10,
is_active BOOLEAN DEFAULT TRUE
);


